language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
sudo: required
dist: xenial
env:
  global:
    - PACKAGE="unikernels"
    - TESTS=false
  matrix:
    - OCAML_VERSION=4.07 POST_INSTALL_HOOK="make ci MODE=unix"
    - OCAML_VERSION=4.07 POST_INSTALL_HOOK="make ci MODE=hvt"
    - OCAML_VERSION=4.07 POST_INSTALL_HOOK="make ci MODE=xen"
    - OCAML_VERSION=4.07 POST_INSTALL_HOOK="make ci MODE=virtio"
    - OCAML_VERSION=4.07 POST_INSTALL_HOOK="make ci MODE=qubes"
